version: '3.8'

services:
  arn:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7777:7777/tcp"  # TCP port for reliable communication
      - "7778:7778/udp"  # UDP port for discovery broadcasts
    environment:
      - ARN_TCP_ADDR=:7777
      - ARN_UDP_ADDR=:7778
    healthcheck:
      test: ["CMD", "/arn-server", "-health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - arn-network

networks:
  arn-network:
    name: arn-network
    driver: bridge
