version: '3.8'

services:
  arn-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7777:7777/tcp"
      - "7778:7778/udp"
    environment:
      - ARN_TCP_ADDR=:7777
      - ARN_UDP_ADDR=:7778
    healthcheck:
      test: ["CMD", "/arn-server", "-health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  coupon-ai:
    build:
      context: .
      dockerfile: examples/coupon_ai/Dockerfile
    environment:
      - ARN_SERVER_HOST=arn-server
      - ARN_TCP_PORT=7777
      - MCP_ENABLED=true
    depends_on:
      - arn-server

  # Example MCP data source
  retail-data:
    build:
      context: examples/retail-data
      dockerfile: Dockerfile
    environment:
      - MCP_PROTOCOL=1.0
      - ARN_SERVER_HOST=arn-server
      - ARN_TCP_PORT=7777
    depends_on:
      - arn-server

networks:
  default:
    name: arn-network
    driver: bridge
